[tool.black]
target-version = ['py310']

[tool.isort]
profile = "black"
force_single_line = true

[tool.curlylint.rules]
image_alt = true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "superlists.settings"
python_files = "tests.py test_*.py *_tests.py"
filterwarnings = [
    "ignore::UserWarning",
]
