# Generated by Django 4.1.7 on 2023-04-13 14:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="text",
            field=models.TextField(default=""),
        ),
    ]
